name: Build Project

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          
      - name: Create custom Maven Settings.xml
        uses: whelk-io/maven-settings-xml-action@v18
        with:
          output_file: custom_maven_settings.xml
          servers: '[{ "id": "github-packages-compas", "username": "OWNER", "password": "${{ secrets.GITHUB_TOKEN }}" }]'

      - name: Build with Maven
        run: ./mvnw -s custom_maven_settings.xml -B clean verify

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          # Set the context to use the current directory and not execute it's own git checkout.
          context: .
          push: false

      - run: echo "🍏 This job's status is ${{ job.status }}."